platform :ios, '8.0'

target '9DZB' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'MJExtension', '~> 3.0.13'
  pod 'Masonry', '~> 1.0.2'
  pod 'MJRefresh', '~> 3.1.15'
  pod 'NullSafe', '~> 1.2.2'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'FMDB', '~> 2.6.2'
  pod 'UMengUShare/Social/Sina'
  pod 'UMengUShare/Social/ReducedWeChat'
  pod 'UMengUShare/Social/QQ'
  pod 'UMengAnalytics'
  pod 'SocketRocket'
  pod 'Toast', '~> 3.1.0'
  pod 'KSYMediaPlayer_iOS', '~> 2.9.0'
  pod 'HyphenateLite'
  pod 'SVProgressHUD', '~> 2.2.2'
end


